#----------- 在ansible deployment host创建admin kubectl kubeconfig文件: /root/.kube/config
#本文档的所有操作均在 ansible deployment host 节点上执行，然后远程分发文件和执行命令；
#本文档只需要部署一次，生成的 kubeconfig 文件是通用的，可以拷贝到需要执行 kubectl 命令的机器，重命名为 ~/.kube/config；
- name: 删除原有kubeconfig
  file: path=/root/.kube/config state=absent
  ignore_errors: true

- name: 准备kubectl使用的admin证书签名请求
  template: src=admin-csr.json.j2 dest={{ ansible_dir }}/ssl/admin-csr.json

- name: 创建admin证书与私钥
  shell: "cd {{ ansible_dir }}/ssl && {{ k8s_dir }}/bin/cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes admin-csr.json | {{ k8s_dir }}/bin/cfssljson -bare admin"

- name: 设置集群参数
  shell: "{{ k8s_dir }}/bin/kubectl config set-cluster {{ CLUSTER_NAME }} \
        --certificate-authority={{ ansible_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }}"

- name: 设置客户端认证参数
  shell: "{{ k8s_dir }}/bin/kubectl config set-credentials admin \
        --client-certificate={{ ansible_dir }}/ssl/admin.pem \
        --embed-certs=true \
        --client-key={{ ansible_dir }}/ssl/admin-key.pem"

- name: 设置上下文参数
  shell: "{{ k8s_dir }}/bin/kubectl config set-context {{ CLUSTER_NAME }} \
        --cluster={{ CLUSTER_NAME }} --user=admin"

- name: 选择默认上下文
  shell: "{{ k8s_dir }}/bin/kubectl config use-context {{ CLUSTER_NAME }}"