- block:
    - name: 下载 group:read rbac 文件
      copy: src=read-group-rbac.yaml dest=/tmp/read-group-rbac.yaml

    - name: 创建group:read rbac 绑定
      shell: "{{ k8s_dir }}/bin/kubectl apply -f /tmp/read-group-rbac.yaml"

    - name: 准备kubectl使用的read证书签名请求
      template: src=read-csr.json.j2 dest={{ ansible_dir }}/ssl/read-csr.json

    - name: 创建read证书与私钥
      shell: "cd {{ ansible_dir }}/ssl && {{ k8s_dir }}/bin/cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            -profile=kubernetes read-csr.json | {{ k8s_dir }}/bin/cfssljson -bare read"

    - name: 设置只读kubeconfig集群参数
      shell: "{{ k8s_dir }}/bin/kubectl config set-cluster {{ CLUSTER_NAME }} \
            --certificate-authority={{ ansible_dir }}/ssl/ca.pem \
            --embed-certs=true \
            --server={{ KUBE_APISERVER }} \
            --kubeconfig=/root/.kube/read.config"

    - name: 设置只读kubeconfig客户端认证参数
      shell: "{{ k8s_dir }}/bin/kubectl config set-credentials read \
            --client-certificate={{ ansible_dir }}/ssl/read.pem \
            --embed-certs=true \
            --client-key={{ ansible_dir }}/ssl/read-key.pem \
            --kubeconfig=/root/.kube/read.config"

    - name: 设置只读kubeconfig上下文参数
      shell: "{{ k8s_dir }}/bin/kubectl config set-context {{ CLUSTER_NAME }} \
            --cluster={{ CLUSTER_NAME }} --user=read \
            --kubeconfig=/root/.kube/read.config"

    - name: 选择只读kubeconfig默认上下文
      shell: "{{ k8s_dir }}/bin/kubectl config use-context {{ CLUSTER_NAME }} \
            --kubeconfig=/root/.kube/read.config"
  tags: create_ro_kctl_cfg