- name: 准备kube-scheduler 证书签名请求
  template: src=kube-scheduler-csr.json.j2 dest={{ ansible_dir }}/ssl/kube-scheduler-csr.json

- name: 创建 kube-scheduler证书与私钥
  shell: "cd {{ ansible_dir }}/ssl && {{ k8s_dir }}/bin/cfssl gencert \
        -ca=ca.pem \
        -ca-key=ca-key.pem \
        -config=ca-config.json \
        -profile=kubernetes kube-scheduler-csr.json | {{ k8s_dir }}/bin/cfssljson -bare kube-scheduler"

- name: 设置集群参数
  shell: "{{ k8s_dir }}/bin/kubectl config set-cluster kubernetes \
        --certificate-authority={{ ansible_dir }}/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }} \
        --kubeconfig={{ ansible_dir }}/kube-scheduler.kubeconfig"

- name: 设置认证参数
  shell: "{{ k8s_dir }}/bin/kubectl config set-credentials system:kube-scheduler \
        --client-certificate={{ ansible_dir }}/ssl/kube-scheduler.pem \
        --client-key={{ ansible_dir }}/ssl/kube-scheduler-key.pem \
        --embed-certs=true \
        --kubeconfig={{ ansible_dir }}/kube-scheduler.kubeconfig"

- name: 设置上下文参数
  shell: "{{ k8s_dir }}/bin/kubectl config set-context default \
        --cluster=kubernetes \
        --user=system:kube-scheduler \
        --kubeconfig={{ ansible_dir }}/kube-scheduler.kubeconfig"

- name: 选择默认上下文
  shell: "{{ k8s_dir }}/bin/kubectl config use-context default \
   --kubeconfig={{ ansible_dir }}/kube-scheduler.kubeconfig"